### ISSUE TITLE
Specify the committer name and email while pushing

### ISSUE THREAD

**Issue by stefan-lacatus** [vrosu/thingworx-gitbackup-extension#1]
When pushing a commit from the UI, it would be good to specify the committer name and email.
Another way to do it is to use the currently logged in user data.

This is especially important in scenarios where you have multiple users working on the same system, in the same project. This way, each user can push on his own, while keeping a clean commit history.

**Comment by vrosu** [comment]
Currently the committer name and email are the ones specified at the level of the Git Thing. You would like to have the ability to overwrite that default for each commit, if I read this right? If yes, would you be fine if I would not implement persistence for the "last used name and email" -> meaning always needing to overwrite the default values?

**Comment by stefan-lacatus** [comment]
To be honest, the best approach would be to have a checkbox to "Use User Extension values". This way, the default behaviour would be the original one, and the new behaviour would be to use the values specified on the user extension of the logged in user that's doing the commit.

**Comment by vrosu** [comment]
Adding a comment that persistence for this setting should be per user, at the user Extension level.

**Comment by vrosu** [comment]
In progress.

**Comment by vrosu** [comment]
Done & documentation was updated.
