### ISSUE TITLE
ExportProjectData fails with error "Name or service not known"

### ISSUE THREAD

**Issue by cwatsonptc** [vrosu/thingworx-gitbackup-extension#10]
ExportProjectData works until the end, but when execution this code:

```JavaScript
var ExportURL = target.baseURL + "/DataExporter?Accept=" + encodeURIComponent("application/octet-stream") + "&path=" + encodeURIComponent(iftbl_ConfigurationRow.FileRepoPath) + "&repositoryName=" + encodeURIComponent(iftbl_ConfigurationRow.FileRepository) + "&searchTags=" + encodeURIComponent("Applications:" + ProjectName);
var params2 = {
    headers: {
        "appKey": target.appKey
    } /* JSON */ ,
    ignoreSSLErrors: true /* BOOLEAN */ ,
    url: ExportURL /* STRING */
};

// result: STRING
var str_ExportResult = Resources["ContentLoaderFunctions"].GetText(params2);
```

With the error:

```
 Error executing service ExportProjectData. Message :: cwatson1l2: Name or service not known - See Script Error Log for more details.
```

Checking ScriptErrorLog it outputs:

```

2020-03-23 14:37:35.071+0000 [L: ERROR] [O: S.c.q.l.c.Logger] [I: TS_MachineBuilder_Git] [U: Administrator] [S: ] [P: ] [T: http-nio-8080-exec-5] Error in: TS_MachineBuilder_Git.ExportProjectData javascript service
        at ExportProjectData:124
```

Where line 124 is var str_ExportResult = Resources["ContentLoaderFunctions"].GetText(params2);

The ExportURL is:
http://cwatson1l2:8080/Thingworx/DataExporter?Accept=application%2Foctet-stream&path=%2Fgit&repositoryName=TS_MachineBuilder_GFR&searchTags=Applications%3ATS.MachineBuilder_PR

The Tag Applications:TS.MachineBuilder_PR does not exist; however, changing it to a tag that does exist does not help.

**Comment by vrosu** [comment]
Before going on the issue a couple of comments about what happens there.
In ThingWorx we can't export Data in bulk (rows from Streams or DataTables) by Project. The Export Data functionality does a bulk export based only on the Model Tag. The code loops through all the entities that are tagged with the specific Project and tags them with a Model Tag that will be autocreated the first time it is used (the Applications vocabulary is Dynamic). Then, the platform bulk data exporter should work fine.

Issue comments:
-this should be pretty sure the fact that the hostname "cwatson1l2" can not be resolved ThingWorx instance host operating system. 

Try and replace this line:
var ExportURL = target.baseURL + "/DataExporter?Accept....
with
var ExportURL = "http://127.0.0.1:8080/DataExporter?Accept....

Note to self: it's unclear why I'm not using the loopback by default in this service.

**Comment by cwatsonptc** [comment]
Adding the server to the hosts file to resolve to 127.0.0.1 fixed the problem.
Thanks

The Server in the URL comes from:

```javascript
var target = Things["ExtensionImportTargets"].importTargets.getRow(0);
var ExportURL = target.baseURL + "/DataExporter?Accept=" + encodeURIComponent("application/octet-stream") + "&path=" + encodeURIComponent(iftbl_ConfigurationRow.FileRepoPath) + "&repositoryName=" + encodeURIComponent(iftbl_ConfigurationRow.FileRepository) + "&searchTags=" + encodeURIComponent("Applications:" + ProjectName);
```

Where ExtensionImportTargets.importTargets contains:

| name     | baseURL                          | appKey   |
| --------  | -------------------------------- | -------- |
| localhost | http://cwatson1l2:8080/Thingworx | ******** |

Does this need fixing in the underlying ExtensionExport Code?

**Comment by vrosu** [comment]
Not really. Now I remember why the code looks like that.
The ExtensionImportTargets is Pierre Tessier's extension that allows Extension Import/Export. In order for that to work you are requested to manually add in that infotable an URL through which your server is accessible.
In order to remove that manual step, my GitBackup.Main.Mashup detects via Javascript the current hostname and port and uses that to populate the infotable.
Regarding the IP address, I'm not sure if a Tomcat connector will always listen to 127.0.0.1
Regarding the port, if ThingWorx is behind a firewall/reverse proxy, you don't know the internal connector port to which the localhost will listen.
That's why I use what is almost always guaranteed to work: the browser's hostname and port

**Comment by cwatsonptc** [comment]
Ok -so we need to ensure the server can resolve it's host name.

**Comment by vrosu** [comment]
Yes.
