### ISSUE TITLE
importing to 9.0.1 fails

### ISSUE THREAD

**Issue by heteneik** [vrosu/thingworx-gitbackup-extension#13]
Hi,

Trying to import the extension to 9.0.1 and got the following error:

 Extension : infotableselector_ExtensionPackage is already installed. infotableselector_ExtensionPackage:2.2.0 is not compatible, you must remove infotableselector_ExtensionPackage:3.0.1 first.

**Comment by vrosu** [comment]
Can you please raise this issue in the new repository listed in the readme.md?
We'll continue the conversation there once you add it.
Thanks!
