### ISSUE TITLE
Error when trying to use Import Extension

### ISSUE THREAD

**Issue by Seppel1985** [vrosu/thingworx-gitbackup-extension#14]
Hi Vladimir,

can you please help?
I get the following error, when trying to import an extension.
Application.Log - There are no additional errors in the log
**Error in ContentLoader.postMultiPart: check your inputs! Certificate for <win-0rf92o7nrfs.localdomain> doesn't match any of the subject alternative names: []**

The extension I try to install is the mail extension, see screenshot.
I guess it has something to do with the server, but all certificates are installed.

Also I can install the extension in a manual way using the standard thingworx import.

Thank you & best regards,
Sebastian 
![2020-09-15_18-51-36](https://user-images.githubusercontent.com/14169085/93240869-f49e9a00-f784-11ea-9e92-4f93b3ed8cea.png)

**Comment by vrosu** [comment]
Absolutely np to help, but I will ask to open this issue in the new Git repository where the extension is maintained going forward,  [here](https://github.com/PTCInc/thingworx-gitbackup-extension)
I will close this issue now here, and will continue the discussion on the other repo.
