### ISSUE TITLE
Problems setting up build environment

### ISSUE THREAD

**Issue by remixed123** [vrosu/thingworx-gitbackup-extension#2]
I have gotten stuck on step 4 in the list below, can you provide any additional details?
------------------
This is an Ant Eclipse project that uses the ThingWorx Eclipse plugin, available in the PTC Marketplace.
1.	Install the ThingWorx Eclipse plugin
2.	Download the ThingWorx Extension SDK version 8.1.0. It should be a zip file.
3.	Import the project: Use the File Menu / Import / Projects from Folder or Archive.
4.	Right click on the property name and in the ThingWorx Extension tab setup the path to the Extension SDK zip file.
5.	Execute the ant build task. The project uses a customized version of the ant build script that is generated by the ThingWorx Eclipse plugin.

**Comment by vrosu** [comment]
Fixed a typo in the documentation. It reads now as:
"After import, right click on the project name in the left hand side of the screen and in the ThingWorx Extension tab setup the path to the Extension SDK zip file."
