### ISSUE TITLE
Unable to export extensions

### ISSUE THREAD

**Issue by code4me-xx** [vrosu/thingworx-gitbackup-extension#6]
Hi,

Thank you for a great plugin, it is a shame it was removed from the market place. I've just made a fresh upgrade to Thingworx 8.5.3 and instaled the latest version of GitBackup 3.0.1. 

When I try to do an extension export it newer finishes and there isn't anything exported. I've reverted to 1.3.1.

Regards Peter

**Comment by vrosu** [comment]
Hi Peter,
I tested just now this feature with 8.5.3 and it worked. My OS: Redhat 7.6, JVM 1.8.0_231 64 bit, Tomcat 9.0.27, accessed via HTTPS.
One thing I have noticed is that if you have the ThingworxStorage and ThingworxBackupStorage setup as relative paths you will have some issues - I think I've added this in the documentation.
Can you check the rest of your platform-settings.json compared to mine?

My platform-settings.json looks like this:
{
	"PlatformSettingsConfig": {
		"BasicSettings": {
			_"BackupStorage": "/ThingworxBackupStorage",_
			"DatabaseLogRetentionPolicy": 7,
			"EnableBackup": true,
			"EnableHA": false,
			"EnableSystemLogging": false,
			"EnableSSO": false,
			_"FileRepositoryRoot": "/ThingworxStorage",_
			"HTTPRequestHeaderMaxLength": 2000,
			"HTTPRequestParameterMaxLength": 2000,
			"InternalAesCryptographicKeyLength": 128,
			_"Storage": "/ThingworxStorage",_
			"ScriptTimeout": 30
		},
		"AdministratorUserSettings": {
			"InitialPassword": "**redacted**"
		},
		"ContentTypeSettings": {
			"supportedMediaEntityContentTypes": ["image/svg+xml", "image/png", "image/gif", "image/bmp", "image/jpeg", "application/pdf", "image/vnd.microsoft.icon"]
		},
		"ExtensionPackageImportPolicy": {
			"importEnabled": true,
			"allowJarResources": true,
			"allowJavascriptResources": true,
			"allowCSSResources": true,
			"allowJSONResources": true,
			"allowWebAppResources": true,
			"allowEntities": true,
			"allowExtensibleEntities": true
		},
		"SolutionCentralSettings": {
		      "SolutionCentralHost": "sc.thingworx.com",
		      "SolutionCentralPort":"443",
		      "KeyStorePath": "/ThingworxPlatform/sc-keystore",
		      "KeyStorePass": "**redacted**"
		}
	},
	"PersistenceProviderPackageConfigs": {
		"PostgresPersistenceProviderPackage": {
			"ConnectionInformation": {
				"acquireIncrement": 5,
				"acquireRetryAttempts": 3,
				"acquireRetryDelay": 10000,
				"checkoutTimeout": 1000000,
				"driverClass": "org.postgresql.Driver",
				"fetchSize": 5000,
				"idleConnectionTestPeriod": 60,
				"initialPoolSize": 5,
				"jdbcUrl": "jdbc:postgresql://localhost:5432/thingworx",
				"maxConnectionAge": 0,
				"maxIdleTime": 0,
				"maxIdleTimeExcessConnections": 300,
				"maxPoolSize": 100,
				"maxStatements": 100,
				"minPoolSize": 5,
				"numHelperThreads": 8,
				"password": "encrypt.db.password",
				"testConnectionOnCheckout": false,
				"unreturnedConnectionTimeout": 0,
				"username": "twadmin"
			},
			"StreamProcessorSettings": {
				"maximumBlockSize": 2500,
				"maximumQueueSize": 250000,
				"maximumWaitTime": 10000,
				"numberOfProcessingThreads": 5,
				"scanRate": 5,
				"sizeThreshold": 1000
			},
			"ValueStreamProcessorSettings": {
				"maximumBlockSize": 2500,
				"maximumQueueSize": 500000,
				"maximumWaitTime": 10000,
				"numberOfProcessingThreads": 5,
				"scanRate": 5,
				"sizeThreshold": 1000
			},
			"PersistentPropertyProcessorSettings": {
				"maximumBlockSize": 2500,
				"maximumWaitTime": 1000,
				"maximumQueueSize": 100000,
				"numberOfProcessingThreads": 20,
				"scanRate": 25,
				"sizeThreshold": 1000
			}
		}
	}
}

**Comment by code4me-xx** [comment]
Hi,

i'm actually running on windows and my platform file contains the settings below (Just recommended)

{
	"PlatformSettingsConfig": {
		"BasicSettings": {
			"BackupStorage": "D:\\ThingworxBackupStorage",
			"DatabaseLogRetentionPolicy": 7,
			"EnableBackup": true,
			"EnableHA": false,
			"EnableSystemLogging": false,
			"HTTPRequestHeaderMaxLength": 2000,
			"HTTPRequestParameterMaxLength": 2000,
			"Storage": "D:\\ThingworxStorage"
		},
		"ContentTypeSettings": {
			"supportedMediaEntityContentTypes": [
				"image/svg+xml",
				"image/png",
				"image/gif",
				"image/bmp",
				"image/jpeg",
				"application/pdf",
				"image/vnd.microsoft.icon"
			]
		},
        "ExtensionPackageImportPolicy": {
             "importEnabled": true,
             "allowJarResources": true,
             "allowJavascriptResources": true,
             "allowCSSResources": true,
             "allowJSONResources": true,
             "allowWebAppResources": true,
             "allowEntities": true,
             "allowExtensibleEntities": true
        }
	},
	"PersistenceProviderPackageConfigs": {
		"PostgresPersistenceProviderPackage": {
			"ConnectionInformation": {
				"jdbcUrl": "jdbc:postgresql://localhost:5432/thingworx",
				"password": "xyz",
				"username": "xyz"
			}
		}
	}
}

Regards Peter

**Comment by vrosu** [comment]
Questions:
1. Have you did this in the following order: a. removed all the existing GitThings b. removed 1.3.1 c. install 3.0.1 d. restarted the server ?
2. Anything in all your logs when you try to do extension export?
3. Do you do extension export via Mashup or via service invocation?
4. Try to manually run your GitThing's GetConfiguration service and paste that result here (redacting private info, of course). That's the service which passes input parameters to the service that exports extensions

**Comment by code4me-xx** [comment]
Hi,

It looked like performing your stem 1 again, making sure that everything was removed from the old installation before installing the version helped. After an additional restart everything worked.

Thank you for the fast and accurate response.

Regards Peter
